version: '3.8'

services:
  client:
    volumes:
      - type: bind
        source: ./source/client/src
        target: /var/client/src
    build:
      context: ./source/client
      dockerfile: Dockerfile.dev
      args:
        - IMAGE_SERVER_PROTOCOL=http
        - IMAGE_SERVER_HOSTNAME=server
        - IMAGE_SERVER_PORT=1337
        - API_ADDRESS_SERVER_SIDE=http://server:1337/api
        - API_ADDRESS_CLIENT_SIDE=${WEBSITE_ORIGIN}:1337/api
    ports:
      - "8080:3000"
    depends_on:
      - server

  server:
    build:
      context: ./source/server
      args:
        - ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
        - ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "1337:1337"
