import Head from 'next/head';
import { Roboto } from '@next/font/google';
import { twMerge } from 'tailwind-merge';
import { Search, ScrollButton } from '@/components';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });
const robotoLight = Roboto({ weight: '300', subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AlphaGallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={twMerge(
          roboto.className,
          'flex min-h-screen w-screen flex-col items-center',
          'bg-chineseBlack text-snow'
        )}
      >
        <div
          className="flex min-h-screen w-screen flex-col items-center
        justify-center bg-chineseBlackVoid"
        >
          <div
            className="flex w-full flex-1 flex-col items-center
        justify-center"
          >
            <div
              className={twMerge(
                robotoLight.className,
                'text-center text-6xl text-coralRed sm:text-7xl '
              )}
            >
              Alpha Gallery
            </div>
            <div className="mt-4 text-begonia">
              Explore and Upload Images just by a few clicks...
            </div>
            <Search containerClassName="mt-16" />
          </div>

          <ScrollButton containerClassName="mb-4" />
        </div>

        <div
          className="flex min-h-screen w-screen flex-col items-center
        justify-center bg-gradient-to-b from-chineseBlackVoid to-chineseBlack"
        ></div>
      </main>
    </>
  );
}
